run:
  concurrency: 4
  timeout: 10m

linters:
  disable-all: true
  enable-all: false
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - gofumpt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - ineffassign
    - interfacebloat
    - maintidx
    - misspell
    - nakedret
    - prealloc
    - reassign
    - revive
    - staticcheck
    - typecheck
    - unused
    - usetesting

linters-settings:
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters:
        - gosec
      text: "^(G107|G204|G306):"
    - path: 'e2e/'
      linters:
        # The usetesting linter shows a lot of lint for env var handling and
        # tempdir creation in e2e tests. It's not really valid lint - the e2e
        # tests were explicitly written to keep tempdirs in a per-run outer dir,
        # and env var handling is complicated by the e2e.SingularityCmd
        # execution flow etc.
        - usetesting
